# Generated by Django 5.2.8 on 2025-11-23 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='lugar',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
        migrations.AddField(
            model_name='evento',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.participante'),
        ),
    ]
