"""nueva columna deleteAt en categoria

Revision ID: 09cf58331043
Revises: ddccb417a687
Create Date: 2025-09-28 09:57:20.704245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cf58331043'
down_revision = 'ddccb417a687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria_model', schema=None) as batch_op:
        batch_op.drop_column('deletedAt')

    # ### end Alembic commands ###
