"""cambio nombre tabla

Revision ID: 18679d359b23
Revises: 09cf58331043
Create Date: 2025-09-28 10:04:35.605330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18679d359b23'
down_revision = '09cf58331043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('categoria_model', 'categorias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('categorias', 'categoria_model')
    # ### end Alembic commands ###
