"""modificacion columna disponible

Revision ID: 3dcd678340bc
Revises: 1fc8271807e1
Create Date: 2025-10-05 10:51:27.538040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcd678340bc'
down_revision = '1fc8271807e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('disponible',
              existing_type=sa.BOOLEAN(),
              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('disponible',
              existing_type=sa.BOOLEAN(),
              nullable=False)

    # ### end Alembic commands ###
