"""cambie tipo de datos y nombre a columna llamada orden

Revision ID: e654775be69b
Revises: 18679d359b23
Create Date: 2025-10-04 09:55:08.116573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e654775be69b'
down_revision = '18679d359b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('orden', new_column_name='posicion',
                existing_type=sa.INTEGER(), type_=sa.FLOAT())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('posicion', new_column_name='orden',
                existing_type=sa.FLOAT(), type_=sa.INTEGER())

    # ### end Alembic commands ###
